export const TELEWORK_SUBMISSION = "TELEWORK_SUBMISSION";
export const TELEWORK_APPROVAL = "TELEWORK_APPROVAL";

export const SL_REVIEW_SUBMISSION = "SL_REVIEW_SUBMISSION";
export const SL_REVIEW_RESUBMISSION = "SL_REVIEW_RESUBMISSION";
