apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.name }}
  annotations:
    meta.release/v: v1
spec:
  host: {{ .Values.ffawebUrl }}
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}
  wildcardPolicy: None