apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.name }}
  annotations:
    meta.release/v: v1
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}