services:
  manners:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    working_dir: /app
    environment:
     
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_DEPLOYMENT: ${AZURE_OPENAI_DEPLOYMENT}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      FLASK_PORT: ${FLASK_PORT:-8080}
      API_KEY: ${API_KEY:-your_default_api_key}
    volumes:
      - .:/app
    restart: unless-stopped

  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_ENV=development
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY:-your_default_secret_key}
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/superset.db}
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/report.db:/app/report.db:rw
    restart: unless-stopped

volumes:
  superset_home:
