"""add_table_release_note_map_user

Revision ID: 467d5693dcba
Revises: 4df0837c3435
Create Date: 2022-11-01 07:27:00.066120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467d5693dcba'
down_revision = '4df0837c3435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_note_map_user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('read_by', sa.String(length=256), nullable=False),
    sa.Column('release_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_note_id'], ['release_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_note_map_user')
    # ### end Alembic commands ###
