"""add_supportedidp_column_in_form_process

Revision ID: bc8ad1f790b5
Revises: eebaa19e739b
Create Date: 2023-02-15 07:09:19.166616

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bc8ad1f790b5'
down_revision = 'eebaa19e739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('supported_idp', sa.String(length=1024), nullable=True,
                                                   comment='comma separated supported IDPs'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_process_mapper', 'supported_idp')
    # ### end Alembic commands ###