apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Values.releaseName }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  annotations:
    meta.release/v: v1
  name: {{ .Values.name }}
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: {{ .Values.appName }}