apiVersion: template.openshift.io/v1
kind: Template
label:
  app: forms-flow-ai
metadata:
  name: forms-flow-documents
objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      host: ${FORMSFLOW_DOC_API_URL}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
      wildcardPolicy: None

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      selector:
        app: ${NAME}
      ports:
        - protocol: TCP
          port: 5006
          targetPort: 5006

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        app: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 700
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${NAME}
        spec:
          containers:
            - env:
              - name: KEYCLOAK_URL
                valueFrom:
                  secretKeyRef:
                    key: keycloak_url
                    name: ${FORMSFLOW_CONFIG_NAME}-secret
              - name: KEYCLOAK_URL_REALM
                valueFrom:
                  secretKeyRef:
                    key: keycloak_realm
                    name: ${FORMSFLOW_CONFIG_NAME}-secret
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    key: DATABASE_URL
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: JWT_OIDC_AUDIENCE
                valueFrom:
                  secretKeyRef:
                    key: JWT_OIDC_AUDIENCE
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: JWT_OIDC_CACHING_ENABLED
                valueFrom:
                  configMapKeyRef:
                    key: JWT_OIDC_CACHING_ENABLED
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: JWT_OIDC_ISSUER
                valueFrom:
                  configMapKeyRef:
                    key: JWT_OIDC_ISSUER
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: JWT_OIDC_JWKS_URI
                valueFrom:
                  configMapKeyRef:
                    key: JWT_OIDC_JWKS_URI
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: JWT_OIDC_WELL_KNOWN_CONFIG
                valueFrom:
                  configMapKeyRef:
                    key: JWT_OIDC_WELL_KNOWN_CONFIG
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMSFLOW_API_CORS_ORIGINS
                value: "*"
              - name: FORMIO_URL
                valueFrom:
                  secretKeyRef:
                    key: FORMIO_URL
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMIO_ROOT_EMAIL
                valueFrom:
                  secretKeyRef:
                    key: FORMIO_ROOT_EMAIL
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMIO_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: FORMIO_ROOT_PASSWORD
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: KEYCLOAK_ENABLE_CLIENT_AUTH
                valueFrom:
                  secretKeyRef:
                    key: KEYCLOAK_ENABLE_CLIENT_AUTH
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMSFLOW_API_URL
                valueFrom:
                  configMapKeyRef:
                    key: WEB_API_BASE_URL
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMSFLOW_DOC_API_URL
                valueFrom:
                  configMapKeyRef:
                    key: FORMSFLOW_DOC_API_URL
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: CHROME_DRIVER_PATH
                valueFrom:
                  configMapKeyRef:
                    key: CHROME_DRIVER_PATH
                    name: ${FORMSFLOW_CONFIG_NAME}-config
              - name: FORMIO_JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: FORMIO_JWT_SECRET
                    name: ${FORMSFLOW_CONFIG_NAME}-config
          image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${NAME}:${TAG_NAME}
          name: ${NAME}
          ports:
            - containerPort: 5006
          resources: {}
          stdin: true
          tty: true
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_NAMESPACE}"
              name: "${NAME}:${TAG_NAME}"
          type: ImageChange
    status: {}

parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms-flow-documents
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description:
      The namespace of the OpenShift project containing the imagestream for
      the application.
    value: ""
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
  - name: FORMSFLOW_CONFIG_NAME
    description: Secrets are referred from this.
    required: true
    value: forms-flow-ai
  - name: FORMSFLOW_SECRET
    description: Secrets are referred from this.
    required: true
    value: forms-flow-ai
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: latest
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 750m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
  - name: KEYCLOAK_REALM
    displayName: KEYCLOAK_REALM
    description: KEYCLOAK_REALM
    required: false
  - name: KEYCLOAK_URL
    description: The URL used to connect to the OIDC provider.
    required: false
