kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: forms-flow-web
  annotations:
    description: ""
    tags: forms-flow-web
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/bcgov/digital-journeys
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: DGJ-6_SBC-Setup
  - name: SOURCE_CONTEXT_DIR
    displayName: Git context directory
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: /forms-flow-web
objects:
-
  apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: forms-flow-web
    labels:
      app: forms-flow-web
  spec:
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 4Gi
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 3
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
    output:
      to:
        kind: ImageStreamTag
        name: 'forms-flow-web:${TAG}'
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile.prod
        pullSecret:
          name: artifactory-credentials
        env:
          - name: FORMIO_SOURCE_REPO_URL
            value: 'https://github.com/AOT-Technologies/forms-flow-ai.git'
          - name: FORMIO_SOURCE_REPO_BRANCH
            value: v4.0.4

    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange

-
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: forms-flow-web