kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-digital-journeys-content-sanitiser
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-backup
  volumeMode: Filesystem