apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: helm-forms-flow-forms
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations: null
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
      spec:
        containers:
        - env:
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                key: DEBUG
                name: ${FORMIO_SECRET}-secret
          - name: NODE_CONFIG
            valueFrom:
              secretKeyRef:
                key: NODE_CONFIG
                name: ${FORMIO_SECRET}-secret
          - name: ROOT_EMAIL
            valueFrom:
              secretKeyRef:
                key: formio_root_email
                name: ${FORMIO_SECRET}-secret
          - name: ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: formio_root_password
                name: ${FORMIO_SECRET}-secret
          - name: FORMIO_DOMAIN
            valueFrom:
              secretKeyRef:
                key: FORMIO_DOMAIN
                name: ${FORMIO_SECRET}-secret
          - name: FORMIO_JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: formio_jwt_secret
                name: ${FORMIO_SECRET}-secret
          image: image-registry.openshift-image-registry.svc:5000/${TOOLS_WORKSPACE}/${NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              path: /ops/healthz
              port: 3001
              scheme: HTTP
            timeoutSeconds: 1
          name: ${NAME}
          ports:
          - containerPort: 3001
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              path: /ops/readyz
              port: 3001
              scheme: HTTP
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${IMAGE_TAG}
          namespace: ${TOOLS_WORKSPACE}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    selector:
      app: ${NAME}
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${FFA_FORMS_URL}
    port:
      targetPort: "3001"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  displayName: Name
  name: NAME
  required: true
  value: forms-flow-forms
- description: The namespace of the OpenShift project containing the imagestream for
    the application.
  displayName: Image Namespace Tools
  name: TOOLS_WORKSPACE
  required: true
  value: ""
- description: Secrets are referred from this.
  name: FORMIO_SECRET
  required: true
  value: forms-flow-ai
- description: Forms Flow AI Forms URL
  displayName: FFA_FORMS_URL
  name: FFA_FORMS_URL
  required: true
- description: The TAG name for this environment, e.g., dev, test, prod
  displayName: Environment TAG name
  name: IMAGE_TAG
  required: true
  value: ""
- description: The resources CPU request (in cores) for this build.
  displayName: Resources CPU Request
  name: CPU_REQUEST
  required: true
  value: 100m
- description: The resources CPU limit (in cores) for this build.
  displayName: Resources CPU Limit
  name: CPU_LIMIT
  required: true
  value: 750m
- description: The resources Memory request (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 100Mi
- description: The resources Memory limit (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 2Gi
- description: Formio needs an email login
  displayName: Formio admin email
  name: FORMIO_ADMIN_EMAIL
  required: true
  value: admin@example.com
- description: Formio needs a default password to login
  displayName: Formio default password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: FORMIO_ADMIN_PASSWORD
  required: true