apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    meta.release/v: v1
spec:
  ports:
    - name: "{{ .Values.ports.servicePortName }}"
      protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Values.appName }}
