apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    meta.release/v: v1
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: {{ .Values.route.weight }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
  port:
    targetPort: {{ .Values.ports.containerPort }}
