---
apiVersion: v1
kind: Template
labels:
  app: ${NAME}-${INSTANCE}
  app.kubernetes.io/component: redis
  app.kubernetes.io/instance: ${INSTANCE}
  app.kubernetes.io/name: redis
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/part-of: ${NAME}-${INSTANCE}
  app.kubernetes.io/version: "6"
  template: ${NAME}-secret-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${INSTANCE}-${NAME}-secret
    stringData:
      clustermode: ${CLUSTER_MODE}
      password: ${PASSWORD}
      redis.conf: |
        appendonly ${APPEND_ONLY}
        cluster-enabled ${CLUSTER_MODE}
        cluster-require-full-coverage no
        cluster-node-timeout 15000
        cluster-config-file /data/nodes.conf
        cluster-migration-barrier 1
        masterauth ${PASSWORD}
        masteruser default
        protected-mode no
        requirepass ${PASSWORD}
        save 900 1
        save 300 10
        save 60 10000
    type: Opaque
parameters:
  - name: NAME
    description: The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
    value: redis
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
  - name: APPEND_ONLY
    # https://redis.io/topics/persistence
    description: The file format mode that Redis will save in (no for RDB, yes for AOF)
    displayName: Redis Persistence Mode
    required: true
    value: "no"
  - name: CLUSTER_MODE
    # https://redis.io/topics/cluster-tutorial
    description: Run Redis in standalone mode or in cluster mode
    displayName: Redis Cluster Mode
    required: true
    value: "no"
  - name: PASSWORD
    description: Password of the application database
    displayName: Application Database Password
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true