# Author: Shibin Thomas
version: "3.7"

volumes:
  postgres:
  
networks:
  forms-flow-network:
    driver: 'bridge'

services:
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    restart: unless-stopped
    container_name: keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
      - ./themes/formsflow:/opt/jboss/keycloak/themes/formsflow
      
    command: 
      - "start-dev"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USER:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
    ports:
      - 4000:8080
    networks:
      - forms-flow-network
   
