name: Push forms-flow-documents to silver registry

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - production
  push:
    branches: [dev, test, main]
    paths:
      - "forms-flow-documents/**"

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-documents


jobs:
  build-and-push-image-to-dockerhub:
    if: github.event_name == 'push' && github.repository == 'bcgov/digital-journeys'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: formsflow/forms-flow-documents
            context: forms-flow-documents
            dockerfile: Dockerfile.prod
            name: forms-flow-documents
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set version
        if: ${{github.event.inputs.environment == 'dev' || github.ref == 'refs/heads/dev'}}
        working-directory: .
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Set version
        if: ${{github.event.inputs.environment == 'test' || github.ref == 'refs/heads/test'}}
        working-directory: .
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - name: Set version
        if: ${{github.event.inputs.environment == 'production' || github.ref == 'refs/heads/master'}}
        working-directory: .
        run: |
          VER=$(cat VERSION)
          VER=${VER/-alpha/''}
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - run: echo ${{ env.VERSION }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          tags: ${{ env.VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.name }}
      
      - name: Build and push Docker image dev
        if: ${{github.event.inputs.environment == 'dev' || github.ref == 'refs/heads/dev'}}
        uses: docker/build-push-action@v2
        with:
          context: forms-flow-documents
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image test
        if: ${{github.event.inputs.environment == 'test' || github.ref == 'refs/heads/test'}}
        uses: docker/build-push-action@v2
        with:
          context: forms-flow-documents
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image production
        if: ${{github.event.inputs.environment == 'production' || github.ref == 'refs/heads/master'}}
        uses: docker/build-push-action@v2
        with:
          context: forms-flow-documents
          push: true
          tags: ${{ steps.meta.outputs.tags }}, formsflow/forms-flow-documents:latest
          labels: ${{ steps.meta.outputs.labels }}
