# Static Deploy On Openshift
# Builds and Deploys merged PR's to persistent pods/services/routes/etc in the OpenShift Dev environment.
name: Test GA workflow for image tagging
  
on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  push:
    # Edit to the branch(es) you want to build and deploy on each push.
    branches: [ test-ga-env-vars ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - production

jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Vars
        if: ${{!github.event.inputs.environment}}
        run: |
          echo "BUILD_TAG=dev" >> $GITHUB_ENV  
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Build ID: ${{ github.event.number }}
          echo OC CLI Version: $(oc version)
          cat $GITHUB_ENV
          echo 1 ${{ env.BUILD_TAG }}
      - name: Print Build tag
        run: echo "In checkEnv ${{ env.BUILD_TAG }}"

   # #Build the app

  build:
    name: Build APP
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged == true}}
    env:
      BUILD_ID: ${{ github.event.number }}
      BUILD_NAMESPACE: d89793-tools
      BRANCH: main
      BUILD_TAG: ${{ github.event.inputs.environment }}
      APP: forms-flow-web
      API: forms-flow-webapi
    steps:
      # Checkout the PR branch
      - name: Set Build TAG
        if: ${{!github.event.inputs.environment}}
        run: echo "BUILD_TAG=dev" >> $GITHUB_ENV
      - name: Print env
        run: |
          echo BUILD ID: $BUILD_ID
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo BRANCH: $BRANCH
          echo "In build ${{ env.BUILD_TAG }}"